# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/corduroy/all/corduroy.rbi
#
# corduroy-0.1.0

class TestStack < Minitest::Test
  def setup; end
  def stack_fibonacci(fib_n); end
  def test_bracket_checker; end
  def test_fibonacci; end
  def test_reverse_a_word; end
  def test_stack; end
  extend T::Sig
end
class TestStack::BracketChecker
  def initialize(string:); end
  def validate!; end
end
class TestStack::BracketChecker::InvalidDelimiterError < StandardError
end
