# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/corduroy/all/corduroy.rbi
#
# corduroy-0.1.0

class TestTrie < Minitest::Test
  def setup; end
  def test_search; end
  def test_starts_with; end
end
