AllCops:
  TargetRubyVersion: 3.1.1

Lint/RedundantWithIndex:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WhileUntilModifier:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
